### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by heycait**
Fix typo - not sure how much giant hash structures like to be 'massaged' :)

Although the description is still not as clear as it could be..

### CODE REVIEW

**Comment by rwz** [comment]
Thanks!

**Comment by davidrunger** [comment]
I believe that the original wording was correct (albeit maybe slightly unconventional) and that this PR should be reverted.

The sentence in question:

> Jbuilder gives you a simple DSL for declaring JSON structures that beats (massaging|messaging) giant hash structures.

I don't really even know what "messaging giant hash structures" means, but I do know what "massaging giant hash structures means" (the previous wording). Here is a relevant definition of "massage" from http://www.thefreedictionary.com/massaging that applies in this context:

> to manipulate so as to produce a desired result, ex: "to massage data"

That's exactly what Jbuilder does; it manipulates data.

@rwz Let's revert.

**Comment by davidrunger** [comment]
PR to revert: https://github.com/rails/jbuilder/pull/367

**Comment by heycait** [comment]
Hmm I've never heard that usage before. But yes Merriam-Webster lists a similar definition:

"to change (numbers, data, etc.) in a dishonest way in order to deceive people" http://www.merriam-webster.com/dictionary/massage

Either way I think it needs better wording.

**Comment by davidrunger** [comment]
> I think it needs better wording.

@heycait Any suggestions?

**Comment by heycait** [comment]
Or even just say what you said.

Jbuilder gives you a simple DSL for declaring JSON structures that beats manipulating giant hash structures.

**Comment by davidrunger** [comment]
I agree that is better. 👍

**Comment by davidrunger** [comment]
@heycait @rwz  I updated https://github.com/rails/jbuilder/pull/367 to use "manipulating".

**Pull request merged**
