### PR TITLE
Why don't we generate jbuilder templates for Rails 5?

### PR DESCRIPTION
**Pull request by amatsuda**
The patch has no test, but I confirmed that it works on my local rails/master app.

### CODE REVIEW

**Comment by rwz** [comment]
Well, Jbuilder also depends on activesupport "< 5". I'm not sure I'm comfortable announcing that Rails 5 is supported just yet, and that PR kind of does that. Could we at wait until they at least release a beta?

**Comment by rwz** [comment]
I'll leave this PR open and merge it to give credit once Rails 5 beta is available.

**Comment by amatsuda** [comment]
@rwz Thank you for the consideration, but `activesupport "< 5"` would not really be a problem in this case.
Because rails master is already versioned as `5.0.0.alpha` 
https://github.com/rails/rails/blob/ed9589ee62c3e19971d620aeab9c7e811cf154c4/RAILS_VERSION 
which will actually match both `<5` and `>= 4` thanks to RubyGems' cleverness.

```ruby
Gem::Version.new('5.0.0.alpha') < Gem::Version.new('5')
#=> true
```

**Comment by rwz** [comment]
Alright, that makes sense. :)

**Comment by rwz** [comment]
Released 2.2.11

**Comment by amatsuda** [comment]
@rwz Thank you! :star2:

**Pull request merged**
